<?
$idc = htmlentities($tos[id], ENT_QUOTES,'UTF-8');
						//$nombre = 
						//$leveladmin = 
						/*$documentacion = */
						$licencias = 
						$seguro = 
						//$telefono = 
						//$respeto = 
						//$dinero = 
						//$banco = 
						//$trabajo = 
						//$faccion = 
						//$rango = 
						//$interior =
						//$virtual = 
						$casa = 
						$coches = 
						$negocio = 
						//$x = 
						//$y = 
						//$z = 
						//$angulo = 
						$inventario = 
						$armas = 
						$ammo = 
						$bloq = 
						$adv = 
						//$cert = 
						//$jugando = 
						//$skin = 
						//$sexo = 
						//$edad = 
						//$vida = 
						//$chaleco = 
						//$email = 